### ISSUE TITLE
微信公众号应用开发从入门到精通 书上面给出的百度网盘下载地址已经失效

### ISSUE THREAD

**Issue by tlemar** [spetacular/weixin#1]
示例代码的百度网盘地址已经失效了， 发送邮件到booksaga@126.com 也没有人回复。

请提供新的下载地址。 

ps： 其实可以将代码放到github上， 这样更加的方便

**Comment by spetacular** [comment]
源代码的下载地址是百度云分享：http://pan.baidu.com/s/1iBKZW
